# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payable', '0007_update_recipient_related_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoicer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contact_info', models.TextField(help_text='At least the address.')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
