# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


default_invoicer = None
def ensure_default_invoicer(apps, schema):
    global default_invoicer
    Invoicer = apps.get_model('payable', 'Invoicer')

    try:
        default_invoicer = Invoicer.objects.get(is_default=True)
    except Invoicer.DoesNotExist:
        default_invoicer = Invoicer.objects.create(
            name="Default Invoicer Name",
            contact_info="1234 Sesame St\nNo Place, KS",
            is_default=True,
        )

    print('successfully set default invoicer')

class Migration(migrations.Migration):

    dependencies = [
        ('payable', '0008_create_model_invoicer'),
    ]

    operations = [
        migrations.RunPython(
            ensure_default_invoicer,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payable.Invoicer'),
            preserve_default=False,
        ),
    ]
