# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payable', '0009_assign_default_invoicer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicer',
            old_name='contact_info',
            new_name='address',
        ),
        migrations.AddField(
            model_name='invoicer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoicer',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
