# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payable', '0010_granular_invoicer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='has_been_sent',
            field=models.BooleanField(default=False),
        ),
    ]
