# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 08:15
from __future__ import unicode_literals

from django.db import migrations


def mark_sent(apps, schema):
    Invoice = apps.get_model('payable', 'Invoice')
    Invoice.objects.all().update(has_been_sent=True)

class Migration(migrations.Migration):

    dependencies = [
        ('payable', '0011_invoice_has_been_sent'),
    ]

    operations = [
        migrations.RunPython(
            mark_sent,
            elidable=True,
        )
    ]
