# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payable', '0012_mark_invoices_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.TextField(blank=True),
        ),
    ]
